soccer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('standings.urls')),
]

standings/urls.py
from django.urls import path

from . import views

app_name = 'standings'
urlpatterns = [
    path('', views.standings, name='standings'),
    path('<int:pk>/', views.owner_page, name='owner'),
    path('<int:pk>/manage/', views.manage, name='manage'),
]

standings/models.py
from django.db import models
from django.shortcuts import reverse

from datetime import datetime
from pytz import utc

# Create your models here.
class Owner(models.Model):
    name = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('standings:owner', args=[self.pk])

class Team(models.Model):
    FRA = 'fra'
    GER = 'ger'
    ITA = 'ita'
    ESP = 'esp'
    ENG = 'eng'
    LEAGUES = (
        (FRA, 'France'),
        (GER, 'Germany'),
        (ITA, 'Italy'),
        (ESP, 'Spain'),
        (ENG, 'England'),
    )
    name = models.CharField(max_length=100, blank=True)
    league = models.CharField(max_length=3, choices=LEAGUES, blank=True)
    goal_diff = models.IntegerField(default=0)
    wins = models.IntegerField(default=0)
    draws = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey('Owner', on_delete=models.CASCADE, blank=True, null=True, related_name="teams")

    def __str__(self):
        return f'{self.name} of {self.league.upper()}'

    def record(self):
        return f'{self.wins}-{self.draws}-{self.losses}'

standings/views.py
from bs4 import BeautifulSoup as BS
from requests import get

from django.contrib.auth.decorators import login_required
from django.db import models
from django.shortcuts import get_object_or_404, render, redirect, reverse

from datetime import datetime
from pytz import utc

from .models import Owner, Team


def standings(request):
    message = ''
    if request.method == "POST":
        if request.POST.get('password') == 'reinhard':
            s = lambda l: BS(get(f'http://www.espn.com/soccer/standings/_/league/{l}.1').text, "html.parser")
            leagues = ['fra', 'ger', 'ita', 'esp', 'eng']
            now = datetime.now(utc)
            for league in leagues:
                soup = s(league)
                for club in soup.find_all(class_="standings-row"):
                    team, created = Team.objects.get_or_create(name=club.find(class_='team-names').text, league=league)
                    if created or (now - team.updated).total_seconds() > 60*60*4:
                        tds = club.find_all('td')
                        team.wins = tds[2].text
                        team.draws = tds[3].text
                        team.losses = tds[4].text
                        team.goal_diff = tds[7].text
                        team.save()
            return redirect('standings:standings')
        else:
            message = 'Please enter the correct password'
    owners = Owner.objects.annotate(
        score=models.Sum('teams__wins')*3+models.Sum('teams__draws'),
        goal_diff=models.Sum('teams__goal_diff')
    ).order_by('-score', '-goal_diff')
    return render(request, 'standings/standings.html', {'message': message, 'owners': owners})

def owner_page(request, pk):
    owner = get_object_or_404(Owner, pk=pk)
    teams = Team.objects.annotate(
        score=models.F('wins')*3+models.F('draws')
    ).order_by('-score', '-goal_diff')
    teams_you = teams.filter(owner=owner)
    teams_none = teams.filter(owner=None)
    return render(request, 'standings/owner.html', {'teams_you': teams_you, 'teams_none': teams_none, 'owner': owner})

def manage(request, pk):
    owner = get_object_or_404(Owner, pk=pk)
    if request.method == "POST":
        post = request.POST.dict()
        post.pop('csrfmiddlewaretoken')
        if post.pop('password') == 'reinhard':
            for key in post:
                team = get_object_or_404(Team, pk=key[1:])
                if team.owner == owner:
                    team.owner = None
                elif team.owner == None:
                    team.owner = owner
                team.save()
    return redirect(owner)

standings/templates/base.html
<h1>Soccer Bot</h1>
<h4>Made by Om Joshi</h4>
<a href="{%url 'standings:standings'%}">Home</a>
{%block body%}
{%endblock%}

standings/templates/standings/owner.html
{%extends 'base.html'%}
{%block body%}
<h2>{{owner.name}}</h2>
<table>
    <tbody>
        <tr>
            <th>Name</th>
            <th>Score</th>
            <th>Goal Differential</th>
            <th>Action</th>
        </tr>
        <tr>
            <th>Teams</th>
            <th>Owned</th>
            <th>By</th>
            <th>You</th>
        </tr>
        {%for team in teams_you%}
        <tr>
            <td>{{team.name}}</td>
            <td>{{team.score}}</td>
            <td>{{team.goal_diff}}</td>
            <td><input type="checkbox" form="manage" name="_{{team.pk}}" id="{{team.pk}}"><label for="{{team.pk}}">- Drop?</label></td>
        </tr>
        {%empty%}
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        {%endfor%}
        <tr>
            <th>Teams</th>
            <th>Owned</th>
            <th>By</th>
            <th>None</th>
        </tr>
        {%for team in teams_none%}
        <tr>
            <td>{{team.name}}</td>
            <td>{{team.score}}</td>
            <td>{{team.goal_diff}}</td>
            <td><input type="checkbox" form="manage" name="_{{team.pk}}" id="{{team.pk}}"><label for="{{team.pk}}">+ Add?</label></td>
        </tr>
        {%empty%}
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
        {%endfor%}
    </tbody>
</table>
<h2>{{message}}</h2>
<form action="{% url 'standings:manage' owner.pk %}" id="manage" method='post'>
    <input type="password" name="password" placeholder="Password" required />
    {%csrf_token%}
    <input type="submit" value="Update Team" />
</form>
{%endblock%}

standings/templates/standings/standings.html
{%extends 'base.html'%}
{%block body%}
<table>
    <tbody>
        <tr>
            <th>Name</th>
            <th>Score</th>
            <th>Goal Differential</th>
        </tr>
        {%for owner in owners%}
        <tr>
            <td><a href="{{owner.get_absolute_url}}">{{owner.name}}</a></td>
            <td>{{owner.score}}</td>
            <td>{{owner.goal_diff}}</td>
        </tr>
        {%endfor%}
    </tbody>
</table>
<h2>{{message}}</h2>
<form action="{% url 'standings:standings' %}" method='post'>
    <input type="password" name="password" placeholder="Password" required />
    {%csrf_token%}
    <input type="submit" value="Update Database" />
</form>
{%endblock%}